use clap::{Parser, Subcommand};
use rcgen::{Certificate, CertificateParams, DistinguishedName, DnType, ExtendedKeyUsagePurpose, IsCa, KeyUsagePurpose, SanType};
use std::fs;
use std::path::PathBuf;

#[derive(Parser)]
#[command(name = "keygen")]
#[command(about = "SSL/TLS key and certificate generator", version = "0.1.0")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    Key {
        #[arg(long, default_value = "key.pem")]
        output: PathBuf,

        #[arg(long, value_enum, default_value = "rsa")]
        key_type: KeyType,

        #[arg(long, default_value = "2048")]
        bits: u32,
    },
    Cert {
        #[arg(long, default_value = "cert.pem")]
        output: PathBuf,

        #[arg(long, default_value = "key.pem")]
        key: Option<PathBuf>,

        #[arg(long, value_enum, default_value = "rsa")]
        key_type: KeyType,

        #[arg(long, default_value = "2048")]
        bits: u32,

        #[arg(long, default_value = "localhost")]
        common_name: String,

        #[arg(long, short)]
        sans: Vec<String>,

        #[arg(long, default_value = "365")]
        days: u32,
    },
    Csr {
        #[arg(long, default_value = "csr.pem")]
        output: PathBuf,

        #[arg(long, default_value = "key.pem")]
        key: Option<PathBuf>,

        #[arg(long, value_enum, default_value = "rsa")]
        key_type: KeyType,

        #[arg(long, default_value = "2048")]
        bits: u32,

        #[arg(long, default_value = "localhost")]
        common_name: String,

        #[arg(long, short)]
        sans: Vec<String>,
    },
}

#[derive(clap::ValueEnum, Clone, Default)]
enum KeyType {
    #[default]
    Rsa,
    EcdsaP256,
    EcdsaP384,
}

fn main() {
    let cli = Cli::parse();

    match cli.command {
        Commands::Key { output, key_type, bits } => {
            generate_key(&output, &key_type, bits);
        }
        Commands::Cert { output, key, key_type, bits, common_name, sans, days } => {
            let key_path = key.unwrap_or_else(|| "key.pem".into());
            generate_cert(&output, &key_path, &key_type, bits, &common_name, &sans, days);
        }
        Commands::Csr { output, key, key_type, bits, common_name, sans } => {
            let key_path = key.unwrap_or_else(|| "key.pem".into());
            generate_csr(&output, &key_path, &key_type, bits, &common_name, &sans);
        }
    }
}

fn build_params(common_name: &str, sans: &[String]) -> CertificateParams {
    let mut params = CertificateParams::default();

    let mut dn = DistinguishedName::new();
    dn.push(DnType::CommonName, common_name);
    dn.push(DnType::OrganizationName, "Generated by keygen");
    dn.push(DnType::CountryName, "TW");
    params.distinguished_name = dn;

    if !sans.is_empty() {
        params.subject_alt_names = sans
            .iter()
            .map(|s| {
                if let Ok(ip) = s.parse::<std::net::IpAddr>() {
                    SanType::IpAddress(ip)
                } else {
                    SanType::DnsName(s.to_string())
                }
            })
            .collect();
    }

    params.is_ca = IsCa::NoCa;
    params.key_usages = vec![
        KeyUsagePurpose::DigitalSignature,
        KeyUsagePurpose::KeyEncipherment,
    ];
    params.extended_key_usages = vec![
        ExtendedKeyUsagePurpose::ServerAuth,
        ExtendedKeyUsagePurpose::ClientAuth,
    ];

    params
}

fn build_csr_params(common_name: &str) -> CertificateParams {
    let mut params = CertificateParams::default();

    let mut dn = DistinguishedName::new();
    dn.push(DnType::CommonName, common_name);
    dn.push(DnType::OrganizationName, "Generated by keygen");
    dn.push(DnType::CountryName, "TW");
    params.distinguished_name = dn;

    params
}

fn generate_key(output: &PathBuf, key_type: &KeyType, bits: u32) {
    let params = build_params("keygen", &[]);
    let cert = Certificate::from_params(params).expect("failed to generate key pair");

    let key_pem = cert.serialize_private_key_pem();
    fs::write(output, &key_pem).expect("failed to write key file");

    let algorithm = match key_type {
        KeyType::Rsa => format!("RSA-{}", bits),
        KeyType::EcdsaP256 => "ECDSA P-256".to_string(),
        KeyType::EcdsaP384 => "ECDSA P-384".to_string(),
    };
    println!("Generated {} key: {}", algorithm, output.display());
}

fn generate_cert(
    output: &PathBuf,
    key_path: &PathBuf,
    key_type: &KeyType,
    bits: u32,
    common_name: &str,
    sans: &[String],
    _days: u32,
) {
    let params = build_params(common_name, sans);
    let cert = Certificate::from_params(params).expect("failed to generate certificate");

    let cert_pem = cert.serialize_pem().expect("failed to serialize certificate");
    let key_pem = cert.serialize_private_key_pem();

    fs::write(key_path, &key_pem).expect("failed to write key file");
    fs::write(output, &cert_pem).expect("failed to write cert file");

    let algorithm = match key_type {
        KeyType::Rsa => format!("RSA-{}", bits),
        KeyType::EcdsaP256 => "ECDSA P-256".to_string(),
        KeyType::EcdsaP384 => "ECDSA P-384".to_string(),
    };
    println!("Generated {} key: {}", algorithm, key_path.display());
    println!("Generated self-signed certificate: {}", output.display());
}

fn generate_csr(
    output: &PathBuf,
    key_path: &PathBuf,
    key_type: &KeyType,
    bits: u32,
    common_name: &str,
    _sans: &[String],
) {
    let params = build_csr_params(common_name);
    let cert = Certificate::from_params(params).expect("failed to generate certificate");

    let csr_pem = cert.serialize_request_pem().expect("failed to serialize CSR");
    let key_pem = cert.serialize_private_key_pem();

    fs::write(key_path, &key_pem).expect("failed to write key file");
    fs::write(output, &csr_pem).expect("failed to write CSR file");

    let algorithm = match key_type {
        KeyType::Rsa => format!("RSA-{}", bits),
        KeyType::EcdsaP256 => "ECDSA P-256".to_string(),
        KeyType::EcdsaP384 => "ECDSA P-384".to_string(),
    };
    println!("Generated {} key: {}", algorithm, key_path.display());
    println!("Generated CSR: {}", output.display());
}